### ISSUE TITLE
Regarding dataset

### ISSUE THREAD

**Issue by ghost** [golden-panther/glaucoma-detector#7]
Where is the dataset for this project?
Can u please tell us

**Comment by golden-panther** [comment]
Due to storage issues. I removed the dataset from drive. So, I mentioned........... if anyone want the dataset. Contact me using linkedin, mail, etc.,

**Comment by ghost** [comment]
Can u please send the link of dataset here

**Comment by golden-panther** [comment]
Contact me via linkedin or mail please. I don't to publish data publicly. (some hosting and storage issues)

**Comment by deepak-hadkar** [comment]
> Due to storage issues. I removed the dataset from drive. So, I mentioned........... if anyone want the dataset. Contact me using linkedin, mail, etc.,

I have mailed you for the same. Please send me the dataset.
Mailid: deepakhadkar143@gmail.com
